all_oxides = {'Sc2O3': {'formation_energy_per_fu': -18.08, 'inv_elements': ['O', 'Sc']},
 'TiO': {'formation_energy_per_fu': -5.07, 'inv_elements': ['O', 'Ti']},
 'Ti2O3': {'formation_energy_per_fu': -14.84, 'inv_elements': ['O', 'Ti']},
 'Ti3O5': {'formation_energy_per_fu': -23.99, 'inv_elements': ['O', 'Ti']},
 'TiO2': {'formation_energy_per_fu': -9.21, 'inv_elements': ['O', 'Ti']},
 'VO': {'formation_energy_per_fu': -4.0979, 'inv_elements': ['O', 'V']},
 'V2O3': {'formation_energy_per_fu': -11.75, 'inv_elements': ['O', 'V']},
 'VO2': {'formation_energy_per_fu': -6.895, 'inv_elements': ['O', 'V']},
 'V2O5': {'formation_energy_per_fu': -14.917, 'inv_elements': ['O', 'V']},
 'CrO': {'formation_energy_per_fu': -3.63, 'inv_elements': ['O', 'Cr']},
 'Cr(OH)2': {'formation_energy_per_fu': -6.09, 'inv_elements': ['O', 'Cr']},
 'Cr2O3': {'formation_energy_per_fu': -11.3, 'inv_elements': ['O', 'Cr']},
 'CrO2': {'formation_energy_per_fu': -5.59, 'inv_elements': ['O', 'Cr']},
 'CrO3': {'formation_energy_per_fu': -5.2, 'inv_elements': ['O', 'Cr']},
 'Mn(OH)2': {'formation_energy_per_fu': -6.37, 'inv_elements': ['O', 'Mn']},
 'MnO': {'formation_energy_per_fu': -3.91, 'inv_elements': ['O', 'Mn']},
 'Mn3O4': {'formation_energy_per_fu': -13.27, 'inv_elements': ['O', 'Mn']},
 'Mn2O3': {'formation_energy_per_fu': -9.21, 'inv_elements': ['O', 'Mn']},
 'MnO2': {'formation_energy_per_fu': -4.82, 'inv_elements': ['O', 'Mn']},
 'FeO': {'formation_energy_per_fu': -2.55, 'inv_elements': ['O', 'Fe']},
 'Fe(OH)2': {'formation_energy_per_fu': -5.01, 'inv_elements': ['O', 'Fe']},
 'Fe3O4': {'formation_energy_per_fu': -10.51, 'inv_elements': ['O', 'Fe']},
 'Fe2O3': {'formation_energy_per_fu': -7.68, 'inv_elements': ['O', 'Fe']},
 'Co(OH)2': {'formation_energy_per_fu': -2.26, 'inv_elements': ['O', 'Co']},
 'Co3O4': {'formation_energy_per_fu': -7.27, 'inv_elements': ['O', 'Co']},
 'Co2O3': {'formation_energy_per_fu': -5.0, 'inv_elements': ['O', 'Co']},
 'CoO2': {'formation_energy_per_fu': -2.25, 'inv_elements': ['O', 'Co']},
 'Ni(OH)2': {'formation_energy_per_fu': -4.7, 'inv_elements': ['O', 'Ni']},
 'NiO': {'formation_energy_per_fu': -2.22, 'inv_elements': ['O', 'Ni']},
 'Ni3O4': {'formation_energy_per_fu': -7.37, 'inv_elements': ['O', 'Ni']},
 'Ni2O3': {'formation_energy_per_fu': -4.87, 'inv_elements': ['O', 'Ni']},
 'NiO2': {'formation_energy_per_fu': -2.23, 'inv_elements': ['O', 'Ni']},
 'Cu2O': {'formation_energy_per_fu': -1.52, 'inv_elements': ['O', 'Cu']},
 'CuO': {'formation_energy_per_fu': -1.32, 'inv_elements': ['O', 'Cu']},
 'Cu(OH)2': {'formation_energy_per_fu': -3.7, 'inv_elements': ['O', 'Cu']},
 'ZnO': {'formation_energy_per_fu': -3.34, 'inv_elements': ['O', 'Zn']},
 'Zn(OH)2': {'formation_energy_per_fu': -5.8, 'inv_elements': ['O', 'Zn']},
 'Y2O3': {'formation_energy_per_fu': -17.4324, 'inv_elements': ['O', 'Y']},
 'Y(OH)3': {'formation_energy_per_fu': -19.259305, 'inv_elements': ['O', 'Y']},
 'Zr(OH)4': {'formation_energy_per_fu': -16.045, 'inv_elements': ['O', 'Zr']},
 'ZrO(OH)2': {'formation_energy_per_fu': -13.50792,
  'inv_elements': ['O', 'Zr']},
 'ZrO2': {'formation_energy_per_fu': -11.128099, 'inv_elements': ['O', 'Zr']},
 'NbO': {'formation_energy_per_fu': -3.92445, 'inv_elements': ['O', 'Nb']},
 'NbO2': {'formation_energy_per_fu': -7.6321, 'inv_elements': ['O', 'Nb']},
 'Nb2O5': {'formation_energy_per_fu': -18.3, 'inv_elements': ['O', 'Nb']},
 'MoO2': {'formation_energy_per_fu': -5.2037, 'inv_elements': ['O', 'Mo']},
 'MoO3': {'formation_energy_per_fu': -9.8437, 'inv_elements': ['O', 'Mo']},
 'TcO2': {'formation_energy_per_fu': -3.828618, 'inv_elements': ['O', 'Tc']},
 'TcO3': {'formation_energy_per_fu': -4.7730882, 'inv_elements': ['O', 'Tc']},
 'Tc2O7': {'formation_energy_per_fu': -9.6502502, 'inv_elements': ['O', 'Tc']},
 'Ru2O3': {'formation_energy_per_fu': -2.945724, 'inv_elements': ['O', 'Ru']},
 'RuO2': {'formation_energy_per_fu': -1.76492, 'inv_elements': ['O', 'Ru']},
 'Ru(OH)3': {'formation_energy_per_fu': -5.1603, 'inv_elements': ['O', 'Ru']},
 'RuO4': {'formation_energy_per_fu': -1.1318, 'inv_elements': ['O', 'Ru']},
 'Ru(OH)4': {'formation_energy_per_fu': -6.6815429,
  'inv_elements': ['O', 'Ru']},
 'Rh2O': {'formation_energy_per_fu': -0.8673, 'inv_elements': ['O', 'Rh']},
 'RhO': {'formation_energy_per_fu': -0.7806, 'inv_elements': ['O', 'Rh']},
 'Rh2O3': {'formation_energy_per_fu': -2.27662, 'inv_elements': ['O', 'Rh']},
 'RhO2': {'formation_energy_per_fu': -0.6505, 'inv_elements': ['O', 'Rh']},
 'PdO': {'formation_energy_per_fu': -0.6639046, 'inv_elements': ['O', 'Pd']},
 'Pd(OH)2': {'formation_energy_per_fu': -3.122, 'inv_elements': ['O', 'Pd']},
 'PdO2': {'formation_energy_per_fu': -0.555928, 'inv_elements': ['O', 'Pd']},
 'PdO3': {'formation_energy_per_fu': 1.0451, 'inv_elements': ['O', 'Pd']},
 'Ag2O': {'formation_energy_per_fu': -0.1121396, 'inv_elements': ['O', 'Ag']},
 'AgOH': {'formation_energy_per_fu': -0.95322998, 'inv_elements': ['O', 'Ag']},
 'AgO': {'formation_energy_per_fu': 0.1127, 'inv_elements': ['O', 'Ag']},
 'Ag2O3': {'formation_energy_per_fu': 0.90197, 'inv_elements': ['O', 'Ag']},
 'Cd(OH)2': {'formation_energy_per_fu': -4.9057824,
  'inv_elements': ['O', 'Cd']},
 'CdO': {'formation_energy_per_fu': -2.447471, 'inv_elements': ['O', 'Cd']},
 'Al(OH)3': {'formation_energy_per_fu': -11.7907, 'inv_elements': ['O', 'Al']},
 'AlH3O3': {'formation_energy_per_fu': -12.02487, 'inv_elements': ['O', 'Al']},
 'Al2O3': {'formation_energy_per_fu': -16.338298, 'inv_elements': ['O', 'Al']},
 'Ga2O3': {'formation_energy_per_fu': -10.28597, 'inv_elements': ['O', 'Ga']},
 'Ga(OH)3': {'formation_energy_per_fu': -8.6295, 'inv_elements': ['O', 'Ga']},
 'In2O3': {'formation_energy_per_fu': -8.516712, 'inv_elements': ['O', 'In']},
 'In(OH)3': {'formation_energy_per_fu': -8.4096029,
  'inv_elements': ['O', 'In']},
 'Sn(OH)2': {'formation_energy_per_fu': -5.09962, 'inv_elements': ['O', 'Sn']},
 'SnO': {'formation_energy_per_fu': -2.66689, 'inv_elements': ['O', 'Sn']},
 'Sn(OH)4': {'formation_energy_per_fu': -9.865336,
  'inv_elements': ['O', 'Sn']},
 'SnO2': {'formation_energy_per_fu': -5.342459, 'inv_elements': ['O', 'Sn']}}

# can also define your own all_oxides in this format; HSE energies here
# in order for this to work correctly, the compositions must be fully simplified
# for example, Al2O3 * 3H2O must go in as Al2H6O6 --> AlH3O3 (with the formation_energy_per_fu also adjusted by the common factor)

# all_oxides = {"Sc2O3": {"formation_energy_per_fu": None,
#                             "inv_elements": ["O", "Sc"],
#                             },
#                   "TiO2": {"formation_energy_per_fu": -9.43,
#                             "inv_elements": ["O", "Ti"],
#                             },
#                   "V2O3": {"formation_energy_per_fu": None,
#                             "inv_elements": ["O", "V"],
#                             },
#                   "Cr2O3": {"formation_energy_per_fu": -10.833,
#                             "inv_elements": ["O", "Cr"],
#                             },
#                   "MnO2": {"formation_energy_per_fu": -4.399,
#                             "inv_elements": ["O", "Mn"],
#                             },
#                   "Fe2O3": {"formation_energy_per_fu": -7.578,
#                             "inv_elements": ["O", "Fe"],
#                             },
#                   "CoO2": {"formation_energy_per_fu": -2.029,
#                             "inv_elements": ["O", "Co"],
#                             },
#                   "NiO2": {"formation_energy_per_fu": -1.343,
#                             "inv_elements": ["O", "Ni"],
#                             },
#                   "Cu": {"formation_energy_per_fu": 0,
#                             "inv_elements": ["O", "Cu"],
#                             },
#                   "ZnO": {"formation_energy_per_fu": None,
#                             "inv_elements": ["O", "Zn"],
#                             }
#              }

all_ions = {'Sc': {'Sc[3+]': {'energy': -6.231423,
   'charge': 3,
   'n_major': 1,
   'major': 'Sc',
   'without_charge': 'Sc',
   'in_consideration': True},
  'Sc(OH)[2+]': {'energy': -8.399629,
   'charge': 2,
   'n_major': 1,
   'major': 'Sc',
   'without_charge': 'Sc(OH)',
   'in_consideration': True}},
 'Ti': {'Ti[2+]': {'energy': -3.25665,
   'charge': 2,
   'n_major': 1,
   'major': 'Ti',
   'without_charge': 'Ti',
   'in_consideration': True},
  'Ti[3+]': {'energy': -3.62524,
   'charge': 3,
   'n_major': 1,
   'major': 'Ti',
   'without_charge': 'Ti',
   'in_consideration': True},
  'TiO[2+]': {'energy': -5.9842,
   'charge': 2,
   'n_major': 1,
   'major': 'Ti',
   'without_charge': 'TiO',
   'in_consideration': True},
  'HTiO3[-]': {'energy': -9.9069658,
   'charge': -1,
   'n_major': 1,
   'major': 'Ti',
   'without_charge': 'HTiO3',
   'in_consideration': True},
  'TiO2[2+]': {'energy': -4.8424708,
   'charge': 2,
   'n_major': 1,
   'major': 'Ti',
   'without_charge': 'TiO2',
   'in_consideration': True}},
 'V': {'VO[2+]': {'energy': -4.7267,
   'charge': 2,
   'n_major': 1,
   'major': 'V',
   'without_charge': 'VO',
   'in_consideration': True},
  'VO2[+]': {'energy': -6.1815546,
   'charge': 1,
   'n_major': 1,
   'major': 'V',
   'without_charge': 'VO2',
   'in_consideration': True},
  'VO3[-]': {'energy': -8.12086,
   'charge': -1,
   'n_major': 1,
   'major': 'V',
   'without_charge': 'VO3',
   'in_consideration': True},
  'VO4[3-]': {'energy': -9.54552588,
   'charge': -3,
   'n_major': 1,
   'major': 'V',
   'without_charge': 'VO4',
   'in_consideration': True},
  'VO4[-]': {'energy': -8.8437,
   'charge': -1,
   'n_major': 1,
   'major': 'V',
   'without_charge': 'VO4',
   'in_consideration': True},
  'V2O7[4-]': {'energy': -17.8249,
   'charge': -4,
   'n_major': 2,
   'major': 'V',
   'without_charge': 'V2O7',
   'in_consideration': True},
  'VOH2O2[3+]': {'energy': -5.42554,
   'charge': 3,
   'n_major': 1,
   'major': 'V',
   'without_charge': 'VOH2O2',
   'in_consideration': True},
  'HVO4[2-]': {'energy': -10.22526,
   'charge': -2,
   'n_major': 1,
   'major': 'V',
   'without_charge': 'HVO4',
   'in_consideration': True},
  'HVO4(aq)': {'energy': -7.72413,
   'charge': 0,
   'n_major': 1,
   'major': 'V',
   'without_charge': 'HVO4',
   'in_consideration': True},
  'H2VO4[+]': {'energy': -7.73715,
   'charge': 1,
   'n_major': 1,
   'major': 'V',
   'without_charge': 'H2VO4',
   'in_consideration': True},
  'HV2O7[3-]': {'energy': -18.5796,
   'charge': -3,
   'n_major': 2,
   'major': 'V',
   'without_charge': 'HV2O7',
   'in_consideration': True},
  'H3V2O7[-]': {'energy': -19.5536601,
   'charge': -1,
   'n_major': 2,
   'major': 'V',
   'without_charge': 'H3V2O7',
   'in_consideration': True},
  'HV10O28[5-]': {'energy': -79.8313,
   'charge': -5,
   'n_major': 10,
   'major': 'V',
   'without_charge': 'HV10O28',
   'in_consideration': True},
  'H2V10O28[4-]': {'energy': -80.0604,
   'charge': -4,
   'n_major': 10,
   'major': 'V',
   'without_charge': 'H2V10O28',
   'in_consideration': False},
  'V[2+]': {'energy': -2.35034,
   'charge': 2,
   'n_major': 1,
   'major': 'V',
   'without_charge': 'V',
   'in_consideration': True},
  'V[3+]': {'energy': -2.605316,
   'charge': 3,
   'n_major': 1,
   'major': 'V',
   'without_charge': 'V',
   'in_consideration': True},
  'HVO[+]': {'energy': -4.8910386,
   'charge': 1,
   'n_major': 1,
   'major': 'V',
   'without_charge': 'HVO',
   'in_consideration': True},
  'VO[+]': {'energy': -4.6828908,
   'charge': 1,
   'n_major': 1,
   'major': 'V',
   'without_charge': 'VO',
   'in_consideration': True},
  'HVO2[+]': {'energy': -6.8680086,
   'charge': 1,
   'n_major': 1,
   'major': 'V',
   'without_charge': 'HVO2',
   'in_consideration': True},
  'HV2O5[-]': {'energy': -15.639268,
   'charge': -1,
   'n_major': 2,
   'major': 'V',
   'without_charge': 'HV2O5',
   'in_consideration': True},
  'H2VO4[-]': {'energy': -10.7879078,
   'charge': -1,
   'n_major': 1,
   'major': 'V',
   'without_charge': 'H2VO4',
   'in_consideration': True}},
 'Cr': {'Cr[2+]': {'energy': -1.82563,
   'charge': 2,
   'n_major': 1,
   'major': 'Cr',
   'without_charge': 'Cr',
   'in_consideration': True},
  'Cr[3+]': {'energy': -2.23325,
   'charge': 3,
   'n_major': 1,
   'major': 'Cr',
   'without_charge': 'Cr',
   'in_consideration': True},
  'CrO4[2-]': {'energy': -7.636421,
   'charge': -2,
   'n_major': 1,
   'major': 'Cr',
   'without_charge': 'CrO4',
   'in_consideration': True},
  'Cr2O7[2-]': {'energy': -13.67704,
   'charge': -2,
   'n_major': 2,
   'major': 'Cr',
   'without_charge': 'Cr2O7',
   'in_consideration': True},
  'Cr(OH)[2+]': {'energy': -4.4665,
   'charge': 2,
   'n_major': 1,
   'major': 'Cr',
   'without_charge': 'Cr(OH)',
   'in_consideration': True},
  'HCrO4[-]': {'energy': -8.018025,
   'charge': -1,
   'n_major': 1,
   'major': 'Cr',
   'without_charge': 'HCrO4',
   'in_consideration': True},
  'Cr(OH)2[+]': {'energy': -6.5570879,
   'charge': 1,
   'n_major': 1,
   'major': 'Cr',
   'without_charge': 'Cr(OH)2',
   'in_consideration': True},
  'CrO2[-]': {'energy': -5.5545095,
   'charge': -1,
   'n_major': 1,
   'major': 'Cr',
   'without_charge': 'CrO2',
   'in_consideration': True},
  'CrO3[3-]': {'energy': -6.2539727,
   'charge': -3,
   'n_major': 1,
   'major': 'Cr',
   'without_charge': 'CrO3',
   'in_consideration': True},
  'H2CrO4(aq)': {'energy': -8.0622563,
   'charge': 0,
   'n_major': 1,
   'major': 'Cr',
   'without_charge': 'H2CrO4',
   'in_consideration': True}},
 'Mn': {'Mn[2+]': {'energy': -2.35901,
   'charge': 2,
   'n_major': 1,
   'major': 'Mn',
   'without_charge': 'Mn',
   'in_consideration': True},
  'Mn[3+]': {'energy': -0.849937,
   'charge': 3,
   'n_major': 1,
   'major': 'Mn',
   'without_charge': 'Mn',
   'in_consideration': True},
  'MnO4[2-]': {'energy': -5.221039,
   'charge': -2,
   'n_major': 1,
   'major': 'Mn',
   'without_charge': 'MnO4',
   'in_consideration': True},
  'MnO4[-]': {'energy': -4.657306,
   'charge': -1,
   'n_major': 1,
   'major': 'Mn',
   'without_charge': 'MnO4',
   'in_consideration': True},
  'MnOH[+]': {'energy': -4.1986,
   'charge': 1,
   'n_major': 1,
   'major': 'Mn',
   'without_charge': 'MnOH',
   'in_consideration': True},
  'Mn(OH)3[-]': {'energy': -7.7145,
   'charge': -1,
   'n_major': 1,
   'major': 'Mn',
   'without_charge': 'Mn(OH)3',
   'in_consideration': True},
  'HMnO2[-]': {'energy': -5.242722,
   'charge': -1,
   'n_major': 1,
   'major': 'Mn',
   'without_charge': 'HMnO2',
   'in_consideration': True}},
 'Fe': {'Fe[2+]': {'energy': -0.880292,
   'charge': 2,
   'n_major': 1,
   'major': 'Fe',
   'without_charge': 'Fe',
   'in_consideration': True},
  'Fe[3+]': {'energy': -0.109711,
   'charge': 3,
   'n_major': 1,
   'major': 'Fe',
   'without_charge': 'Fe',
   'in_consideration': True},
  'FeO2[2-]': {'energy': -3.06055,
   'charge': -2,
   'n_major': 1,
   'major': 'Fe',
   'without_charge': 'FeO2',
   'in_consideration': True},
  'FeOH[+]': {'energy': -2.8738,
   'charge': 1,
   'n_major': 1,
   'major': 'Fe',
   'without_charge': 'FeOH',
   'in_consideration': True},
  'FeOH[2+]': {'energy': -2.424488,
   'charge': 2,
   'n_major': 1,
   'major': 'Fe',
   'without_charge': 'FeOH',
   'in_consideration': True},
  'HFeO2[-]': {'energy': -3.9299597,
   'charge': -1,
   'n_major': 1,
   'major': 'Fe',
   'without_charge': 'HFeO2',
   'in_consideration': True},
  'Fe(OH)2[+]': {'energy': -4.605269,
   'charge': 1,
   'n_major': 1,
   'major': 'Fe',
   'without_charge': 'Fe(OH)2',
   'in_consideration': True},
  'Fe(OH)3(aq)': {'energy': -6.83418,
   'charge': 0,
   'n_major': 1,
   'major': 'Fe',
   'without_charge': 'Fe(OH)3',
   'in_consideration': True},
  'Fe2(OH)2[4+]': {'energy': -4.84285,
   'charge': 4,
   'n_major': 2,
   'major': 'Fe',
   'without_charge': 'Fe2(OH)2',
   'in_consideration': False},
  'FeO2[-]': {'energy': -3.81653,
   'charge': -1,
   'n_major': 1,
   'major': 'Fe',
   'without_charge': 'FeO2',
   'in_consideration': True},
  'FeO4[2-]': {'energy': -4.84312122,
   'charge': -2,
   'n_major': 1,
   'major': 'Fe',
   'without_charge': 'FeO4',
   'in_consideration': True}},
 'Co': {'Co[2+]': {'energy': -0.555061,
   'charge': 2,
   'n_major': 1,
   'major': 'Co',
   'without_charge': 'Co',
   'in_consideration': True},
  'Co[3+]': {'energy': 1.2532,
   'charge': 3,
   'n_major': 1,
   'major': 'Co',
   'without_charge': 'Co',
   'in_consideration': True},
  'HCoO2[-]': {'energy': -3.59489,
   'charge': -1,
   'n_major': 1,
   'major': 'Co',
   'without_charge': 'HCoO2',
   'in_consideration': True},
  'Co(OH)2(aq)': {'energy': -3.8252,
   'charge': 0,
   'n_major': 1,
   'major': 'Co',
   'without_charge': 'Co(OH)2',
   'in_consideration': True}},
 'Ni': {'Ni[2+]': {'energy': -0.4999882,
   'charge': 2,
   'n_major': 1,
   'major': 'Ni',
   'without_charge': 'Ni',
   'in_consideration': True},
  'NiOH[+]': {'energy': -2.35506,
   'charge': 1,
   'n_major': 1,
   'major': 'Ni',
   'without_charge': 'NiOH',
   'in_consideration': True},
  'Ni(OH)2(aq)': {'energy': -4.2084,
   'charge': 0,
   'n_major': 1,
   'major': 'Ni',
   'without_charge': 'Ni(OH)2',
   'in_consideration': True},
  'Ni(OH)3[-]': {'energy': -6.0794,
   'charge': -1,
   'n_major': 1,
   'major': 'Ni',
   'without_charge': 'Ni(OH)3',
   'in_consideration': True},
  'Ni(OH)4[2-]': {'energy': -7.7089,
   'charge': -2,
   'n_major': 1,
   'major': 'Ni',
   'without_charge': 'Ni(OH)4',
   'in_consideration': True},
  'HNiO2[-]': {'energy': -3.6193859,
   'charge': -1,
   'n_major': 1,
   'major': 'Ni',
   'without_charge': 'HNiO2',
   'in_consideration': True},
  'NiO2[2-]': {'energy': -2.78393028,
   'charge': -2,
   'n_major': 1,
   'major': 'Ni',
   'without_charge': 'NiO2',
   'in_consideration': True},
  'NiO(aq)': {'energy': -1.705916156,
   'charge': 0,
   'n_major': 1,
   'major': 'Ni',
   'without_charge': 'NiO',
   'in_consideration': False}},
 'Cu': {'Cu[+]': {'energy': 0.52,
   'charge': 1,
   'n_major': 1,
   'major': 'Cu',
   'without_charge': 'Cu',
   'in_consideration': True},
  'Cu[2+]': {'energy': 0.673445,
   'charge': 2,
   'n_major': 1,
   'major': 'Cu',
   'without_charge': 'Cu',
   'in_consideration': True},
  'CuO2[2-]': {'energy': -1.88634,
   'charge': -2,
   'n_major': 1,
   'major': 'Cu',
   'without_charge': 'CuO2',
   'in_consideration': True},
  'HCuO2[-]': {'energy': -2.663424,
   'charge': -1,
   'n_major': 1,
   'major': 'Cu',
   'without_charge': 'HCuO2',
   'in_consideration': True},
  'CuO(aq)': {'energy': -0.90195872,
   'charge': 0,
   'n_major': 1,
   'major': 'Cu',
   'without_charge': 'CuO',
   'in_consideration': False},
  'CuOH[+]': {'energy': -1.3095746799999999,
   'charge': 1,
   'n_major': 1,
   'major': 'Cu',
   'without_charge': 'CuOH',
   'in_consideration': True}},
 'Zn': {'Zn[2+]': {'energy': -1.525723,
   'charge': 2,
   'n_major': 1,
   'major': 'Zn',
   'without_charge': 'Zn',
   'in_consideration': True},
  'ZnO2[2-]': {'energy': -4.034164,
   'charge': -2,
   'n_major': 1,
   'major': 'Zn',
   'without_charge': 'ZnO2',
   'in_consideration': True},
  'ZnOH[+]': {'energy': -3.41276,
   'charge': 1,
   'n_major': 1,
   'major': 'Zn',
   'without_charge': 'ZnOH',
   'in_consideration': True},
  'HZnO2[-]': {'energy': -4.80908,
   'charge': -1,
   'n_major': 1,
   'major': 'Zn',
   'without_charge': 'HZnO2',
   'in_consideration': True},
  'Zn(OH)2(aq)': {'energy': -5.41841,
   'charge': 0,
   'n_major': 1,
   'major': 'Zn',
   'without_charge': 'Zn(OH)2',
   'in_consideration': True}},
 'Y': {'Y[3+]': {'energy': -7.116051,
   'charge': 3,
   'n_major': 1,
   'major': 'Y',
   'without_charge': 'Y',
   'in_consideration': True},
  'Y(OH)[2+]': {'energy': -9.11079,
   'charge': 2,
   'n_major': 1,
   'major': 'Y',
   'without_charge': 'Y(OH)',
   'in_consideration': True},
  'Y2(OH)2[4+]': {'energy': -18.4514,
   'charge': 4,
   'n_major': 2,
   'major': 'Y',
   'without_charge': 'Y2(OH)2',
   'in_consideration': False}},
 'Zr': {'ZrO[2+]': {'energy': -8.737869,
   'charge': 2,
   'n_major': 1,
   'major': 'Zr',
   'without_charge': 'ZrO',
   'in_consideration': True},
  'Zr[4+]': {'energy': -6.1577,
   'charge': 4,
   'n_major': 1,
   'major': 'Zr',
   'without_charge': 'Zr',
   'in_consideration': True},
  'HZrO3[-]': {'energy': -12.47586,
   'charge': -1,
   'n_major': 1,
   'major': 'Zr',
   'without_charge': 'HZrO3',
   'in_consideration': True}},
 'Nb': {'NbO3[-]': {'energy': -9.66152,
   'charge': -1,
   'n_major': 1,
   'major': 'Nb',
   'without_charge': 'NbO3',
   'in_consideration': True},
  'Nb(OH)4[+]': {'energy': -12.5279,
   'charge': 1,
   'n_major': 1,
   'major': 'Nb',
   'without_charge': 'Nb(OH)4',
   'in_consideration': True},
  'Nb(OH)5(aq)': {'energy': -15.0127,
   'charge': 0,
   'n_major': 1,
   'major': 'Nb',
   'without_charge': 'Nb(OH)5',
   'in_consideration': True}},
 'Mo': {'Mo[3+]': {'energy': -0.598425,
   'charge': 3,
   'n_major': 1,
   'major': 'Mo',
   'without_charge': 'Mo',
   'in_consideration': True},
  'MoO4[2-]': {'energy': -8.9078566,
   'charge': -2,
   'n_major': 1,
   'major': 'Mo',
   'without_charge': 'MoO4',
   'in_consideration': True},
  'HMoO4[-]': {'energy': -9.262575,
   'charge': -1,
   'n_major': 1,
   'major': 'Mo',
   'without_charge': 'HMoO4',
   'in_consideration': True}},
 'Tc': {'Tc[2+]': {'energy': 0.800068,
   'charge': 2,
   'n_major': 1,
   'major': 'Tc',
   'without_charge': 'Tc',
   'in_consideration': True},
  'HTcO4(aq)': {'energy': -6.52434797,
   'charge': 0,
   'n_major': 1,
   'major': 'Tc',
   'without_charge': 'HTcO4',
   'in_consideration': True},
  'TcO4[-]': {'energy': -6.53128623,
   'charge': -1,
   'n_major': 1,
   'major': 'Tc',
   'without_charge': 'TcO4',
   'in_consideration': True}},
 'Ru': {'RuO4[2-]': {'energy': -2.67123,
   'charge': -2,
   'n_major': 1,
   'major': 'Ru',
   'without_charge': 'RuO4',
   'in_consideration': True},
  'RuO4[-]': {'energy': -2.081,
   'charge': -1,
   'n_major': 1,
   'major': 'Ru',
   'without_charge': 'RuO4',
   'in_consideration': True},
  'RuO4(aq)': {'energy': -1.53021,
   'charge': 0,
   'n_major': 1,
   'major': 'Ru',
   'without_charge': 'RuO4',
   'in_consideration': False},
  'Ru(OH)2[2+]': {'energy': -2.21157,
   'charge': 2,
   'n_major': 1,
   'major': 'Ru',
   'without_charge': 'Ru(OH)2',
   'in_consideration': True},
  'H2RuO5': {'energy': -3.508515118,
   'charge': 0,
   'n_major': 1,
   'major': 'Ru',
   'without_charge': 'H2RuO5',
   'in_consideration': True},
  'HRuO5[-]': {'energy': -2.87504,
   'charge': -1,
   'n_major': 1,
   'major': 'Ru',
   'without_charge': 'HRuO5',
   'in_consideration': True},
  'H2RuO5(aq)': {'energy': -3.53851,
   'charge': 0,
   'n_major': 1,
   'major': 'Ru',
   'without_charge': 'H2RuO5',
   'in_consideration': True}},
 'Rh': {'Rh[3+]': {'energy': 2.39,
   'charge': 3,
   'n_major': 1,
   'major': 'Rh',
   'without_charge': 'Rh',
   'in_consideration': True},
  'RhOH[+]': {'energy': -0.793116586,
   'charge': 1,
   'n_major': 1,
   'major': 'Rh',
   'without_charge': 'RhOH',
   'in_consideration': True},
  'RhOH[2+]': {'energy': -0.035557988,
   'charge': 2,
   'n_major': 1,
   'major': 'Rh',
   'without_charge': 'RhOH',
   'in_consideration': True},
  'Rh[2+]': {'energy': 1.21,
   'charge': 2,
   'n_major': 1,
   'major': 'Rh',
   'without_charge': 'Rh',
   'in_consideration': True},
  'RhO(aq)': {'energy': -0.313083748,
   'charge': 0,
   'n_major': 1,
   'major': 'Rh',
   'without_charge': 'RhO',
   'in_consideration': False},
  'RhO[+]': {'energy': 0.136161076,
   'charge': 1,
   'n_major': 1,
   'major': 'Rh',
   'without_charge': 'RhO',
   'in_consideration': True},
  'Rh[+]': {'energy': 0.607,
   'charge': 1,
   'n_major': 1,
   'major': 'Rh',
   'without_charge': 'Rh',
   'in_consideration': True},
  'RhO4[2-]': {'energy': -0.6505,
   'charge': -2,
   'n_major': 1,
   'major': 'Rh',
   'without_charge': 'RhO4',
   'in_consideration': True}},
 'Pd': {'Pd[2+]': {'energy': 1.9731,
   'charge': 2,
   'n_major': 1,
   'major': 'Pd',
   'without_charge': 'Pd',
   'in_consideration': True}},
 'Ag': {'Ag[+]': {'energy': 0.799201,
   'charge': 1,
   'n_major': 1,
   'major': 'Ag',
   'without_charge': 'Ag',
   'in_consideration': True},
  'AgOH(aq)': {'energy': -0.953513,
   'charge': 0,
   'n_major': 1,
   'major': 'Ag',
   'without_charge': 'AgOH',
   'in_consideration': True},
  'Ag(OH)2[-]': {'energy': -2.69725,
   'charge': -1,
   'n_major': 1,
   'major': 'Ag',
   'without_charge': 'Ag(OH)2',
   'in_consideration': True},
  'Ag[2+]': {'energy': 2.7796,
   'charge': 2,
   'n_major': 1,
   'major': 'Ag',
   'without_charge': 'Ag',
   'in_consideration': True},
  'AgO[-]': {'energy': -0.238069,
   'charge': -1,
   'n_major': 1,
   'major': 'Ag',
   'without_charge': 'AgO',
   'in_consideration': True},
  'AgO[+]': {'energy': 2.3373,
   'charge': 1,
   'n_major': 1,
   'major': 'Ag',
   'without_charge': 'AgO',
   'in_consideration': True}},
 'Cd': {'Cd[2+]': {'energy': -0.8057053,
   'charge': 2,
   'n_major': 1,
   'major': 'Cd',
   'without_charge': 'Cd',
   'in_consideration': True},
  'CdO2[2-]': {'energy': -2.94876,
   'charge': -2,
   'n_major': 1,
   'major': 'Cd',
   'without_charge': 'CdO2',
   'in_consideration': True},
  'CdOH[+]': {'energy': -2.70592,
   'charge': 1,
   'n_major': 1,
   'major': 'Cd',
   'without_charge': 'CdOH',
   'in_consideration': True},
  'HCdO2[-]': {'energy': -3.751,
   'charge': -1,
   'n_major': 1,
   'major': 'Cd',
   'without_charge': 'HCdO2',
   'in_consideration': True},
  'Cd(OH)2(aq)': {'energy': -4.58723,
   'charge': 0,
   'n_major': 1,
   'major': 'Cd',
   'without_charge': 'Cd(OH)2',
   'in_consideration': True}},
 'Al': {'Al[3+]': {'energy': -4.9869,
   'charge': 3,
   'n_major': 1,
   'major': 'Al',
   'without_charge': 'Al',
   'in_consideration': True},
  'AlO2[-]': {'energy': -8.7036116,
   'charge': -1,
   'n_major': 1,
   'major': 'Al',
   'without_charge': 'AlO2',
   'in_consideration': True},
  'AlOH[2+]': {'energy': -7.19411,
   'charge': 2,
   'n_major': 1,
   'major': 'Al',
   'without_charge': 'AlOH',
   'in_consideration': True},
  'Al(OH)4[-]': {'energy': -13.45272,
   'charge': -1,
   'n_major': 1,
   'major': 'Al',
   'without_charge': 'Al(OH)4',
   'in_consideration': True}},
 'Ga': {'Ga[2+]': {'energy': -0.9106,
   'charge': 2,
   'n_major': 1,
   'major': 'Ga',
   'without_charge': 'Ga',
   'in_consideration': True},
  'Ga[3+]': {'energy': -1.58713,
   'charge': 3,
   'n_major': 1,
   'major': 'Ga',
   'without_charge': 'Ga',
   'in_consideration': True},
  'GaO3[3-]': {'energy': -6.4179,
   'charge': -3,
   'n_major': 1,
   'major': 'Ga',
   'without_charge': 'GaO3',
   'in_consideration': True},
  'Ga(OH)[2+]': {'energy': -3.94231,
   'charge': 2,
   'n_major': 1,
   'major': 'Ga',
   'without_charge': 'Ga(OH)',
   'in_consideration': True},
  'HGaO3[2-]': {'energy': -7.1117,
   'charge': -2,
   'n_major': 1,
   'major': 'Ga',
   'without_charge': 'HGaO3',
   'in_consideration': True},
  'Ga(OH)2[+]': {'energy': -6.19319,
   'charge': 1,
   'n_major': 1,
   'major': 'Ga',
   'without_charge': 'Ga(OH)2',
   'in_consideration': True},
  'H2GaO3[-]': {'energy': -7.7198,
   'charge': -1,
   'n_major': 1,
   'major': 'Ga',
   'without_charge': 'H2GaO3',
   'in_consideration': True},
  'GaOH[+]': {'energy': -3.8941,
   'charge': 1,
   'n_major': 1,
   'major': 'Ga',
   'without_charge': 'GaOH',
   'in_consideration': True},
  'GaO[+]': {'energy': -3.7033,
   'charge': 1,
   'n_major': 1,
   'major': 'Ga',
   'without_charge': 'GaO',
   'in_consideration': True},
  'GaO2[-]': {'energy': -5.260067,
   'charge': -1,
   'n_major': 1,
   'major': 'Ga',
   'without_charge': 'GaO2',
   'in_consideration': True}},
 'In': {'In[+]': {'energy': -0.13877,
   'charge': 1,
   'n_major': 1,
   'major': 'In',
   'without_charge': 'In',
   'in_consideration': True},
  'In[2+]': {'energy': -0.537715,
   'charge': 2,
   'n_major': 1,
   'major': 'In',
   'without_charge': 'In',
   'in_consideration': True},
  'In[3+]': {'energy': -1.02773,
   'charge': 3,
   'n_major': 1,
   'major': 'In',
   'without_charge': 'In',
   'in_consideration': True},
  'In(OH)[2+]': {'energy': -3.24213,
   'charge': 2,
   'n_major': 1,
   'major': 'In',
   'without_charge': 'In(OH)',
   'in_consideration': True},
  'In(OH)2[+]': {'energy': -5.44243,
   'charge': 1,
   'n_major': 1,
   'major': 'In',
   'without_charge': 'In(OH)2',
   'in_consideration': True},
  'InO2[-]': {'energy': -4.5099,
   'charge': -1,
   'n_major': 1,
   'major': 'In',
   'without_charge': 'InO2',
   'in_consideration': True},
  'InOH[2+]': {'energy': -3.25665,
   'charge': 2,
   'n_major': 1,
   'major': 'In',
   'without_charge': 'InOH',
   'in_consideration': True}},
 'Sn': {'Sn[2+]': {'energy': -0.2721098,
   'charge': 2,
   'n_major': 1,
   'major': 'Sn',
   'without_charge': 'Sn',
   'in_consideration': True},
  'SnOH[+]': {'energy': -2.64192,
   'charge': 1,
   'n_major': 1,
   'major': 'Sn',
   'without_charge': 'SnOH',
   'in_consideration': True},
  'SnO(OH)[+]': {'energy': -4.91315,
   'charge': 1,
   'n_major': 1,
   'major': 'Sn',
   'without_charge': 'SnO(OH)',
   'in_consideration': True},
  'SnO3[2-]': {'energy': -5.9590967,
   'charge': -2,
   'n_major': 1,
   'major': 'Sn',
   'without_charge': 'SnO3',
   'in_consideration': True},
  'HSnO2[-]': {'energy': -4.25,
   'charge': -1,
   'n_major': 1,
   'major': 'Sn',
   'without_charge': 'HSnO2',
   'in_consideration': True},
  'Sn[4+]': {'energy': 0.02819,
   'charge': 4,
   'n_major': 1,
   'major': 'Sn',
   'without_charge': 'Sn',
   'in_consideration': True}}}

expanded_all_ions = {'Sc[3+]': {'energy': -6.231423,
  'charge': 3,
  'n_major': 1,
  'major': 'Sc',
  'without_charge': 'Sc',
  'in_consideration': True},
 'Sc(OH)[2+]': {'energy': -8.399629,
  'charge': 2,
  'n_major': 1,
  'major': 'Sc',
  'without_charge': 'Sc(OH)',
  'in_consideration': True},
 'Ti[2+]': {'energy': -3.25665,
  'charge': 2,
  'n_major': 1,
  'major': 'Ti',
  'without_charge': 'Ti',
  'in_consideration': True},
 'Ti[3+]': {'energy': -3.62524,
  'charge': 3,
  'n_major': 1,
  'major': 'Ti',
  'without_charge': 'Ti',
  'in_consideration': True},
 'TiO[2+]': {'energy': -5.9842,
  'charge': 2,
  'n_major': 1,
  'major': 'Ti',
  'without_charge': 'TiO',
  'in_consideration': True},
 'HTiO3[-]': {'energy': -9.9069658,
  'charge': -1,
  'n_major': 1,
  'major': 'Ti',
  'without_charge': 'HTiO3',
  'in_consideration': True},
 'TiO2[2+]': {'energy': -4.8424708,
  'charge': 2,
  'n_major': 1,
  'major': 'Ti',
  'without_charge': 'TiO2',
  'in_consideration': True},
 'VO[2+]': {'energy': -4.7267,
  'charge': 2,
  'n_major': 1,
  'major': 'V',
  'without_charge': 'VO',
  'in_consideration': True},
 'VO2[+]': {'energy': -6.1815546,
  'charge': 1,
  'n_major': 1,
  'major': 'V',
  'without_charge': 'VO2',
  'in_consideration': True},
 'VO3[-]': {'energy': -8.12086,
  'charge': -1,
  'n_major': 1,
  'major': 'V',
  'without_charge': 'VO3',
  'in_consideration': True},
 'VO4[3-]': {'energy': -9.54552588,
  'charge': -3,
  'n_major': 1,
  'major': 'V',
  'without_charge': 'VO4',
  'in_consideration': True},
 'VO4[-]': {'energy': -8.8437,
  'charge': -1,
  'n_major': 1,
  'major': 'V',
  'without_charge': 'VO4',
  'in_consideration': True},
 'V2O7[4-]': {'energy': -17.8249,
  'charge': -4,
  'n_major': 2,
  'major': 'V',
  'without_charge': 'V2O7',
  'in_consideration': True},
 'VOH2O2[3+]': {'energy': -5.42554,
  'charge': 3,
  'n_major': 1,
  'major': 'V',
  'without_charge': 'VOH2O2',
  'in_consideration': True},
 'HVO4[2-]': {'energy': -10.22526,
  'charge': -2,
  'n_major': 1,
  'major': 'V',
  'without_charge': 'HVO4',
  'in_consideration': True},
 'HVO4(aq)': {'energy': -7.72413,
  'charge': 0,
  'n_major': 1,
  'major': 'V',
  'without_charge': 'HVO4',
  'in_consideration': True},
 'H2VO4[+]': {'energy': -7.73715,
  'charge': 1,
  'n_major': 1,
  'major': 'V',
  'without_charge': 'H2VO4',
  'in_consideration': True},
 'HV2O7[3-]': {'energy': -18.5796,
  'charge': -3,
  'n_major': 2,
  'major': 'V',
  'without_charge': 'HV2O7',
  'in_consideration': True},
 'H3V2O7[-]': {'energy': -19.5536601,
  'charge': -1,
  'n_major': 2,
  'major': 'V',
  'without_charge': 'H3V2O7',
  'in_consideration': True},
 'HV10O28[5-]': {'energy': -79.8313,
  'charge': -5,
  'n_major': 10,
  'major': 'V',
  'without_charge': 'HV10O28',
  'in_consideration': True},
 'H2V10O28[4-]': {'energy': -80.0604,
  'charge': -4,
  'n_major': 10,
  'major': 'V',
  'without_charge': 'H2V10O28',
  'in_consideration': False},
 'V[2+]': {'energy': -2.35034,
  'charge': 2,
  'n_major': 1,
  'major': 'V',
  'without_charge': 'V',
  'in_consideration': True},
 'V[3+]': {'energy': -2.605316,
  'charge': 3,
  'n_major': 1,
  'major': 'V',
  'without_charge': 'V',
  'in_consideration': True},
 'HVO[+]': {'energy': -4.8910386,
  'charge': 1,
  'n_major': 1,
  'major': 'V',
  'without_charge': 'HVO',
  'in_consideration': True},
 'VO[+]': {'energy': -4.6828908,
  'charge': 1,
  'n_major': 1,
  'major': 'V',
  'without_charge': 'VO',
  'in_consideration': True},
 'HVO2[+]': {'energy': -6.8680086,
  'charge': 1,
  'n_major': 1,
  'major': 'V',
  'without_charge': 'HVO2',
  'in_consideration': True},
 'HV2O5[-]': {'energy': -15.639268,
  'charge': -1,
  'n_major': 2,
  'major': 'V',
  'without_charge': 'HV2O5',
  'in_consideration': True},
 'H2VO4[-]': {'energy': -10.7879078,
  'charge': -1,
  'n_major': 1,
  'major': 'V',
  'without_charge': 'H2VO4',
  'in_consideration': True},
 'Cr[2+]': {'energy': -1.82563,
  'charge': 2,
  'n_major': 1,
  'major': 'Cr',
  'without_charge': 'Cr',
  'in_consideration': True},
 'Cr[3+]': {'energy': -2.23325,
  'charge': 3,
  'n_major': 1,
  'major': 'Cr',
  'without_charge': 'Cr',
  'in_consideration': True},
 'CrO4[2-]': {'energy': -7.636421,
  'charge': -2,
  'n_major': 1,
  'major': 'Cr',
  'without_charge': 'CrO4',
  'in_consideration': True},
 'Cr2O7[2-]': {'energy': -13.67704,
  'charge': -2,
  'n_major': 2,
  'major': 'Cr',
  'without_charge': 'Cr2O7',
  'in_consideration': True},
 'Cr(OH)[2+]': {'energy': -4.4665,
  'charge': 2,
  'n_major': 1,
  'major': 'Cr',
  'without_charge': 'Cr(OH)',
  'in_consideration': True},
 'HCrO4[-]': {'energy': -8.018025,
  'charge': -1,
  'n_major': 1,
  'major': 'Cr',
  'without_charge': 'HCrO4',
  'in_consideration': True},
 'Cr(OH)2[+]': {'energy': -6.5570879,
  'charge': 1,
  'n_major': 1,
  'major': 'Cr',
  'without_charge': 'Cr(OH)2',
  'in_consideration': True},
 'CrO2[-]': {'energy': -5.5545095,
  'charge': -1,
  'n_major': 1,
  'major': 'Cr',
  'without_charge': 'CrO2',
  'in_consideration': True},
 'CrO3[3-]': {'energy': -6.2539727,
  'charge': -3,
  'n_major': 1,
  'major': 'Cr',
  'without_charge': 'CrO3',
  'in_consideration': True},
 'H2CrO4(aq)': {'energy': -8.0622563,
  'charge': 0,
  'n_major': 1,
  'major': 'Cr',
  'without_charge': 'H2CrO4',
  'in_consideration': True},
 'Mn[2+]': {'energy': -2.35901,
  'charge': 2,
  'n_major': 1,
  'major': 'Mn',
  'without_charge': 'Mn',
  'in_consideration': True},
 'Mn[3+]': {'energy': -0.849937,
  'charge': 3,
  'n_major': 1,
  'major': 'Mn',
  'without_charge': 'Mn',
  'in_consideration': True},
 'MnO4[2-]': {'energy': -5.221039,
  'charge': -2,
  'n_major': 1,
  'major': 'Mn',
  'without_charge': 'MnO4',
  'in_consideration': True},
 'MnO4[-]': {'energy': -4.657306,
  'charge': -1,
  'n_major': 1,
  'major': 'Mn',
  'without_charge': 'MnO4',
  'in_consideration': True},
 'MnOH[+]': {'energy': -4.1986,
  'charge': 1,
  'n_major': 1,
  'major': 'Mn',
  'without_charge': 'MnOH',
  'in_consideration': True},
 'Mn(OH)3[-]': {'energy': -7.7145,
  'charge': -1,
  'n_major': 1,
  'major': 'Mn',
  'without_charge': 'Mn(OH)3',
  'in_consideration': True},
 'HMnO2[-]': {'energy': -5.242722,
  'charge': -1,
  'n_major': 1,
  'major': 'Mn',
  'without_charge': 'HMnO2',
  'in_consideration': True},
 'Fe[2+]': {'energy': -0.880292,
  'charge': 2,
  'n_major': 1,
  'major': 'Fe',
  'without_charge': 'Fe',
  'in_consideration': True},
 'Fe[3+]': {'energy': -0.109711,
  'charge': 3,
  'n_major': 1,
  'major': 'Fe',
  'without_charge': 'Fe',
  'in_consideration': True},
 'FeO2[2-]': {'energy': -3.06055,
  'charge': -2,
  'n_major': 1,
  'major': 'Fe',
  'without_charge': 'FeO2',
  'in_consideration': True},
 'FeOH[+]': {'energy': -2.8738,
  'charge': 1,
  'n_major': 1,
  'major': 'Fe',
  'without_charge': 'FeOH',
  'in_consideration': True},
 'FeOH[2+]': {'energy': -2.424488,
  'charge': 2,
  'n_major': 1,
  'major': 'Fe',
  'without_charge': 'FeOH',
  'in_consideration': True},
 'HFeO2[-]': {'energy': -3.9299597,
  'charge': -1,
  'n_major': 1,
  'major': 'Fe',
  'without_charge': 'HFeO2',
  'in_consideration': True},
 'Fe(OH)2[+]': {'energy': -4.605269,
  'charge': 1,
  'n_major': 1,
  'major': 'Fe',
  'without_charge': 'Fe(OH)2',
  'in_consideration': True},
 'Fe(OH)3(aq)': {'energy': -6.83418,
  'charge': 0,
  'n_major': 1,
  'major': 'Fe',
  'without_charge': 'Fe(OH)3',
  'in_consideration': True},
 'Fe2(OH)2[4+]': {'energy': -4.84285,
  'charge': 4,
  'n_major': 2,
  'major': 'Fe',
  'without_charge': 'Fe2(OH)2',
  'in_consideration': False},
 'FeO2[-]': {'energy': -3.81653,
  'charge': -1,
  'n_major': 1,
  'major': 'Fe',
  'without_charge': 'FeO2',
  'in_consideration': True},
 'FeO4[2-]': {'energy': -4.84312122,
  'charge': -2,
  'n_major': 1,
  'major': 'Fe',
  'without_charge': 'FeO4',
  'in_consideration': True},
 'Co[2+]': {'energy': -0.555061,
  'charge': 2,
  'n_major': 1,
  'major': 'Co',
  'without_charge': 'Co',
  'in_consideration': True},
 'Co[3+]': {'energy': 1.2532,
  'charge': 3,
  'n_major': 1,
  'major': 'Co',
  'without_charge': 'Co',
  'in_consideration': True},
 'HCoO2[-]': {'energy': -3.59489,
  'charge': -1,
  'n_major': 1,
  'major': 'Co',
  'without_charge': 'HCoO2',
  'in_consideration': True},
 'Co(OH)2(aq)': {'energy': -3.8252,
  'charge': 0,
  'n_major': 1,
  'major': 'Co',
  'without_charge': 'Co(OH)2',
  'in_consideration': True},
 'Ni[2+]': {'energy': -0.4999882,
  'charge': 2,
  'n_major': 1,
  'major': 'Ni',
  'without_charge': 'Ni',
  'in_consideration': True},
 'NiOH[+]': {'energy': -2.35506,
  'charge': 1,
  'n_major': 1,
  'major': 'Ni',
  'without_charge': 'NiOH',
  'in_consideration': True},
 'Ni(OH)2(aq)': {'energy': -4.2084,
  'charge': 0,
  'n_major': 1,
  'major': 'Ni',
  'without_charge': 'Ni(OH)2',
  'in_consideration': True},
 'Ni(OH)3[-]': {'energy': -6.0794,
  'charge': -1,
  'n_major': 1,
  'major': 'Ni',
  'without_charge': 'Ni(OH)3',
  'in_consideration': True},
 'Ni(OH)4[2-]': {'energy': -7.7089,
  'charge': -2,
  'n_major': 1,
  'major': 'Ni',
  'without_charge': 'Ni(OH)4',
  'in_consideration': True},
 'HNiO2[-]': {'energy': -3.6193859,
  'charge': -1,
  'n_major': 1,
  'major': 'Ni',
  'without_charge': 'HNiO2',
  'in_consideration': True},
 'NiO2[2-]': {'energy': -2.78393028,
  'charge': -2,
  'n_major': 1,
  'major': 'Ni',
  'without_charge': 'NiO2',
  'in_consideration': True},
 'NiO(aq)': {'energy': -1.705916156,
  'charge': 0,
  'n_major': 1,
  'major': 'Ni',
  'without_charge': 'NiO',
  'in_consideration': False},
 'Cu[+]': {'energy': 0.52,
  'charge': 1,
  'n_major': 1,
  'major': 'Cu',
  'without_charge': 'Cu',
  'in_consideration': True},
 'Cu[2+]': {'energy': 0.673445,
  'charge': 2,
  'n_major': 1,
  'major': 'Cu',
  'without_charge': 'Cu',
  'in_consideration': True},
 'CuO2[2-]': {'energy': -1.88634,
  'charge': -2,
  'n_major': 1,
  'major': 'Cu',
  'without_charge': 'CuO2',
  'in_consideration': True},
 'HCuO2[-]': {'energy': -2.663424,
  'charge': -1,
  'n_major': 1,
  'major': 'Cu',
  'without_charge': 'HCuO2',
  'in_consideration': True},
 'CuO(aq)': {'energy': -0.90195872,
  'charge': 0,
  'n_major': 1,
  'major': 'Cu',
  'without_charge': 'CuO',
  'in_consideration': False},
 'CuOH[+]': {'energy': -1.3095746799999999,
  'charge': 1,
  'n_major': 1,
  'major': 'Cu',
  'without_charge': 'CuOH',
  'in_consideration': True},
 'Zn[2+]': {'energy': -1.525723,
  'charge': 2,
  'n_major': 1,
  'major': 'Zn',
  'without_charge': 'Zn',
  'in_consideration': True},
 'ZnO2[2-]': {'energy': -4.034164,
  'charge': -2,
  'n_major': 1,
  'major': 'Zn',
  'without_charge': 'ZnO2',
  'in_consideration': True},
 'ZnOH[+]': {'energy': -3.41276,
  'charge': 1,
  'n_major': 1,
  'major': 'Zn',
  'without_charge': 'ZnOH',
  'in_consideration': True},
 'HZnO2[-]': {'energy': -4.80908,
  'charge': -1,
  'n_major': 1,
  'major': 'Zn',
  'without_charge': 'HZnO2',
  'in_consideration': True},
 'Zn(OH)2(aq)': {'energy': -5.41841,
  'charge': 0,
  'n_major': 1,
  'major': 'Zn',
  'without_charge': 'Zn(OH)2',
  'in_consideration': True},
 'Y[3+]': {'energy': -7.116051,
  'charge': 3,
  'n_major': 1,
  'major': 'Y',
  'without_charge': 'Y',
  'in_consideration': True},
 'Y(OH)[2+]': {'energy': -9.11079,
  'charge': 2,
  'n_major': 1,
  'major': 'Y',
  'without_charge': 'Y(OH)',
  'in_consideration': True},
 'Y2(OH)2[4+]': {'energy': -18.4514,
  'charge': 4,
  'n_major': 2,
  'major': 'Y',
  'without_charge': 'Y2(OH)2',
  'in_consideration': False},
 'ZrO[2+]': {'energy': -8.737869,
  'charge': 2,
  'n_major': 1,
  'major': 'Zr',
  'without_charge': 'ZrO',
  'in_consideration': True},
 'Zr[4+]': {'energy': -6.1577,
  'charge': 4,
  'n_major': 1,
  'major': 'Zr',
  'without_charge': 'Zr',
  'in_consideration': True},
 'HZrO3[-]': {'energy': -12.47586,
  'charge': -1,
  'n_major': 1,
  'major': 'Zr',
  'without_charge': 'HZrO3',
  'in_consideration': True},
 'NbO3[-]': {'energy': -9.66152,
  'charge': -1,
  'n_major': 1,
  'major': 'Nb',
  'without_charge': 'NbO3',
  'in_consideration': True},
 'Nb(OH)4[+]': {'energy': -12.5279,
  'charge': 1,
  'n_major': 1,
  'major': 'Nb',
  'without_charge': 'Nb(OH)4',
  'in_consideration': True},
 'Nb(OH)5(aq)': {'energy': -15.0127,
  'charge': 0,
  'n_major': 1,
  'major': 'Nb',
  'without_charge': 'Nb(OH)5',
  'in_consideration': True},
 'Mo[3+]': {'energy': -0.598425,
  'charge': 3,
  'n_major': 1,
  'major': 'Mo',
  'without_charge': 'Mo',
  'in_consideration': True},
 'MoO4[2-]': {'energy': -8.9078566,
  'charge': -2,
  'n_major': 1,
  'major': 'Mo',
  'without_charge': 'MoO4',
  'in_consideration': True},
 'HMoO4[-]': {'energy': -9.262575,
  'charge': -1,
  'n_major': 1,
  'major': 'Mo',
  'without_charge': 'HMoO4',
  'in_consideration': True},
 'Tc[2+]': {'energy': 0.800068,
  'charge': 2,
  'n_major': 1,
  'major': 'Tc',
  'without_charge': 'Tc',
  'in_consideration': True},
 'HTcO4(aq)': {'energy': -6.52434797,
  'charge': 0,
  'n_major': 1,
  'major': 'Tc',
  'without_charge': 'HTcO4',
  'in_consideration': True},
 'TcO4[-]': {'energy': -6.53128623,
  'charge': -1,
  'n_major': 1,
  'major': 'Tc',
  'without_charge': 'TcO4',
  'in_consideration': True},
 'RuO4[2-]': {'energy': -2.67123,
  'charge': -2,
  'n_major': 1,
  'major': 'Ru',
  'without_charge': 'RuO4',
  'in_consideration': True},
 'RuO4[-]': {'energy': -2.081,
  'charge': -1,
  'n_major': 1,
  'major': 'Ru',
  'without_charge': 'RuO4',
  'in_consideration': True},
 'RuO4(aq)': {'energy': -1.53021,
  'charge': 0,
  'n_major': 1,
  'major': 'Ru',
  'without_charge': 'RuO4',
  'in_consideration': False},
 'Ru(OH)2[2+]': {'energy': -2.21157,
  'charge': 2,
  'n_major': 1,
  'major': 'Ru',
  'without_charge': 'Ru(OH)2',
  'in_consideration': True},
 'H2RuO5': {'energy': -3.508515118,
  'charge': 0,
  'n_major': 1,
  'major': 'Ru',
  'without_charge': 'H2RuO5',
  'in_consideration': True},
 'HRuO5[-]': {'energy': -2.87504,
  'charge': -1,
  'n_major': 1,
  'major': 'Ru',
  'without_charge': 'HRuO5',
  'in_consideration': True},
 'H2RuO5(aq)': {'energy': -3.53851,
  'charge': 0,
  'n_major': 1,
  'major': 'Ru',
  'without_charge': 'H2RuO5',
  'in_consideration': True},
 'Rh[3+]': {'energy': 2.39,
  'charge': 3,
  'n_major': 1,
  'major': 'Rh',
  'without_charge': 'Rh',
  'in_consideration': True},
 'RhOH[+]': {'energy': -0.793116586,
  'charge': 1,
  'n_major': 1,
  'major': 'Rh',
  'without_charge': 'RhOH',
  'in_consideration': True},
 'RhOH[2+]': {'energy': -0.035557988,
  'charge': 2,
  'n_major': 1,
  'major': 'Rh',
  'without_charge': 'RhOH',
  'in_consideration': True},
 'Rh[2+]': {'energy': 1.21,
  'charge': 2,
  'n_major': 1,
  'major': 'Rh',
  'without_charge': 'Rh',
  'in_consideration': True},
 'RhO(aq)': {'energy': -0.313083748,
  'charge': 0,
  'n_major': 1,
  'major': 'Rh',
  'without_charge': 'RhO',
  'in_consideration': False},
 'RhO[+]': {'energy': 0.136161076,
  'charge': 1,
  'n_major': 1,
  'major': 'Rh',
  'without_charge': 'RhO',
  'in_consideration': True},
 'Rh[+]': {'energy': 0.607,
  'charge': 1,
  'n_major': 1,
  'major': 'Rh',
  'without_charge': 'Rh',
  'in_consideration': True},
 'RhO4[2-]': {'energy': -0.6505,
  'charge': -2,
  'n_major': 1,
  'major': 'Rh',
  'without_charge': 'RhO4',
  'in_consideration': True},
 'Pd[2+]': {'energy': 1.9731,
  'charge': 2,
  'n_major': 1,
  'major': 'Pd',
  'without_charge': 'Pd',
  'in_consideration': True},
 'Ag[+]': {'energy': 0.799201,
  'charge': 1,
  'n_major': 1,
  'major': 'Ag',
  'without_charge': 'Ag',
  'in_consideration': True},
 'AgOH(aq)': {'energy': -0.953513,
  'charge': 0,
  'n_major': 1,
  'major': 'Ag',
  'without_charge': 'AgOH',
  'in_consideration': True},
 'Ag(OH)2[-]': {'energy': -2.69725,
  'charge': -1,
  'n_major': 1,
  'major': 'Ag',
  'without_charge': 'Ag(OH)2',
  'in_consideration': True},
 'Ag[2+]': {'energy': 2.7796,
  'charge': 2,
  'n_major': 1,
  'major': 'Ag',
  'without_charge': 'Ag',
  'in_consideration': True},
 'AgO[-]': {'energy': -0.238069,
  'charge': -1,
  'n_major': 1,
  'major': 'Ag',
  'without_charge': 'AgO',
  'in_consideration': True},
 'AgO[+]': {'energy': 2.3373,
  'charge': 1,
  'n_major': 1,
  'major': 'Ag',
  'without_charge': 'AgO',
  'in_consideration': True},
 'Cd[2+]': {'energy': -0.8057053,
  'charge': 2,
  'n_major': 1,
  'major': 'Cd',
  'without_charge': 'Cd',
  'in_consideration': True},
 'CdO2[2-]': {'energy': -2.94876,
  'charge': -2,
  'n_major': 1,
  'major': 'Cd',
  'without_charge': 'CdO2',
  'in_consideration': True},
 'CdOH[+]': {'energy': -2.70592,
  'charge': 1,
  'n_major': 1,
  'major': 'Cd',
  'without_charge': 'CdOH',
  'in_consideration': True},
 'HCdO2[-]': {'energy': -3.751,
  'charge': -1,
  'n_major': 1,
  'major': 'Cd',
  'without_charge': 'HCdO2',
  'in_consideration': True},
 'Cd(OH)2(aq)': {'energy': -4.58723,
  'charge': 0,
  'n_major': 1,
  'major': 'Cd',
  'without_charge': 'Cd(OH)2',
  'in_consideration': True},
 'Al[3+]': {'energy': -4.9869,
  'charge': 3,
  'n_major': 1,
  'major': 'Al',
  'without_charge': 'Al',
  'in_consideration': True},
 'AlO2[-]': {'energy': -8.7036116,
  'charge': -1,
  'n_major': 1,
  'major': 'Al',
  'without_charge': 'AlO2',
  'in_consideration': True},
 'AlOH[2+]': {'energy': -7.19411,
  'charge': 2,
  'n_major': 1,
  'major': 'Al',
  'without_charge': 'AlOH',
  'in_consideration': True},
 'Al(OH)4[-]': {'energy': -13.45272,
  'charge': -1,
  'n_major': 1,
  'major': 'Al',
  'without_charge': 'Al(OH)4',
  'in_consideration': True},
 'Ga[2+]': {'energy': -0.9106,
  'charge': 2,
  'n_major': 1,
  'major': 'Ga',
  'without_charge': 'Ga',
  'in_consideration': True},
 'Ga[3+]': {'energy': -1.58713,
  'charge': 3,
  'n_major': 1,
  'major': 'Ga',
  'without_charge': 'Ga',
  'in_consideration': True},
 'GaO3[3-]': {'energy': -6.4179,
  'charge': -3,
  'n_major': 1,
  'major': 'Ga',
  'without_charge': 'GaO3',
  'in_consideration': True},
 'Ga(OH)[2+]': {'energy': -3.94231,
  'charge': 2,
  'n_major': 1,
  'major': 'Ga',
  'without_charge': 'Ga(OH)',
  'in_consideration': True},
 'HGaO3[2-]': {'energy': -7.1117,
  'charge': -2,
  'n_major': 1,
  'major': 'Ga',
  'without_charge': 'HGaO3',
  'in_consideration': True},
 'Ga(OH)2[+]': {'energy': -6.19319,
  'charge': 1,
  'n_major': 1,
  'major': 'Ga',
  'without_charge': 'Ga(OH)2',
  'in_consideration': True},
 'H2GaO3[-]': {'energy': -7.7198,
  'charge': -1,
  'n_major': 1,
  'major': 'Ga',
  'without_charge': 'H2GaO3',
  'in_consideration': True},
 'GaOH[+]': {'energy': -3.8941,
  'charge': 1,
  'n_major': 1,
  'major': 'Ga',
  'without_charge': 'GaOH',
  'in_consideration': True},
 'GaO[+]': {'energy': -3.7033,
  'charge': 1,
  'n_major': 1,
  'major': 'Ga',
  'without_charge': 'GaO',
  'in_consideration': True},
 'GaO2[-]': {'energy': -5.260067,
  'charge': -1,
  'n_major': 1,
  'major': 'Ga',
  'without_charge': 'GaO2',
  'in_consideration': True},
 'In[+]': {'energy': -0.13877,
  'charge': 1,
  'n_major': 1,
  'major': 'In',
  'without_charge': 'In',
  'in_consideration': True},
 'In[2+]': {'energy': -0.537715,
  'charge': 2,
  'n_major': 1,
  'major': 'In',
  'without_charge': 'In',
  'in_consideration': True},
 'In[3+]': {'energy': -1.02773,
  'charge': 3,
  'n_major': 1,
  'major': 'In',
  'without_charge': 'In',
  'in_consideration': True},
 'In(OH)[2+]': {'energy': -3.24213,
  'charge': 2,
  'n_major': 1,
  'major': 'In',
  'without_charge': 'In(OH)',
  'in_consideration': True},
 'In(OH)2[+]': {'energy': -5.44243,
  'charge': 1,
  'n_major': 1,
  'major': 'In',
  'without_charge': 'In(OH)2',
  'in_consideration': True},
 'InO2[-]': {'energy': -4.5099,
  'charge': -1,
  'n_major': 1,
  'major': 'In',
  'without_charge': 'InO2',
  'in_consideration': True},
 'InOH[2+]': {'energy': -3.25665,
  'charge': 2,
  'n_major': 1,
  'major': 'In',
  'without_charge': 'InOH',
  'in_consideration': True},
 'Sn[2+]': {'energy': -0.2721098,
  'charge': 2,
  'n_major': 1,
  'major': 'Sn',
  'without_charge': 'Sn',
  'in_consideration': True},
 'SnOH[+]': {'energy': -2.64192,
  'charge': 1,
  'n_major': 1,
  'major': 'Sn',
  'without_charge': 'SnOH',
  'in_consideration': True},
 'SnO(OH)[+]': {'energy': -4.91315,
  'charge': 1,
  'n_major': 1,
  'major': 'Sn',
  'without_charge': 'SnO(OH)',
  'in_consideration': True},
 'SnO3[2-]': {'energy': -5.9590967,
  'charge': -2,
  'n_major': 1,
  'major': 'Sn',
  'without_charge': 'SnO3',
  'in_consideration': True},
 'HSnO2[-]': {'energy': -4.25,
  'charge': -1,
  'n_major': 1,
  'major': 'Sn',
  'without_charge': 'HSnO2',
  'in_consideration': True},
 'Sn[4+]': {'energy': 0.02819,
  'charge': 4,
  'n_major': 1,
  'major': 'Sn',
  'without_charge': 'Sn',
  'in_consideration': True}}
